# Go parameters
GOCMD=go
GOINIT=$(GOCMD) mod init discordgo_sui_bot
GOBUILD=$(GOCMD) build
GOCLEAN=$(GOCMD) clean
GOPATH=$(GOCMD) test
GOGET=$(GOCMD) get


# Local settings
BINARY_NAME=discordgo_sui_bot
CONFIG_DIR=../deploy/config
DEPLOY_DIR=../deploy/packages/pi

# For deploying to raspberry pi
PI_USER=
PI_PASS=
PI_DEPLOY_DIR=
PI_IP=
PI_SUPERVISOR_ID=
	
all: get clean build
init:
	$(GOINIT)
get:
	$(GOGET)
build: 
	$(GOBUILD) -o $(BINARY_NAME).exe
clean: 
	$(GOCLEAN)
run:
	$(GOBUILD) -o $(BINARY_NAME)
	./$(BINARY_NAME)
# For raspberry pi
all-pi: pack-pi stop-pi deploy-pi start-pi
pack-pi:
	mkdir -p $(DEPLOY_DIR)
	rm -f $(DEPLOY_DIR)/*
	cp -f $(CONFIG_DIR)/* $(DEPLOY_DIR)
	CGO_ENABLED=0 GOOS=linux GOARCH=arm $(GOBUILD) -o $(DEPLOY_DIR)/$(BINARY_NAME).exe
stop-pi:
	plink $(PI_IP) -l $(PI_USER) -pw $(PI_PASS) 'sudo supervisorctl stop $(PI_SUPERVISOR_ID)'
deploy-pi:
	plink $(PI_IP) -l $(PI_USER) -pw $(PI_PASS) 'mkdir -p $(PI_DEPLOY_DIR)'
	pscp -r -pw $(PI_PASS) $(DEPLOY_DIR)/* $(PI_USER)@$(PI_IP):$(PI_DEPLOY_DIR)
	plink $(PI_IP) -l $(PI_USER) -pw $(PI_PASS) 'chmod 700 -f $(PI_DEPLOY_DIR)/*'
start-pi:
	plink $(PI_IP) -l $(PI_USER) -pw $(PI_PASS) 'sudo supervisorctl start $(PI_SUPERVISOR_ID)'
